// <auto-generated />
using System;
using G_Net_29_EF04.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G_Net_29_EF04.Migrations
{
    [DbContext(typeof(BankDbContext))]
    partial class BankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("G_Net_29_EF04.Models.Account", b =>
            {
                b.Property<string>("AccountNumber").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("AccountType").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("BranchId").HasColumnType("int");
                b.Property<decimal>("CurrentBalance").HasColumnType("decimal(18,2)");
                b.Property<DateTime>("OpeningDate").HasColumnType("datetime2");
                b.HasKey("AccountNumber");
                b.HasIndex("BranchId");
                b.ToTable("Accounts");
            });

            modelBuilder.Entity("G_Net_29_EF04.Models.Branch", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Address").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Code").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("PhoneNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.HasKey("Id");
                b.HasIndex("Code").IsUnique();
                b.ToTable("Branches");
                b.HasData(
                    new { Id = 1, Code = "CAI-01", Name = "Cairo Main Branch",  Address = "10 Tahrir Square, Cairo",     PhoneNumber = "0221234567" },
                    new { Id = 2, Code = "ALX-01", Name = "Alexandria Branch",  Address = "5 Corniche Road, Alexandria", PhoneNumber = "0331234567" },
                    new { Id = 3, Code = "GIZ-01", Name = "Giza Branch",        Address = "15 Haram Street, Giza",       PhoneNumber = "0381234567" });
            });

            modelBuilder.Entity("G_Net_29_EF04.Models.Customer", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Address").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("CustomerType").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("DateOfBirth").HasColumnType("datetime2");
                b.Property<string>("Email").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("NationalId").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("PhoneNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.HasKey("Id");
                b.HasIndex("NationalId").IsUnique();
                b.ToTable("Customers");
            });

            modelBuilder.Entity("G_Net_29_EF04.Models.CustomerAccount", b =>
            {
                b.Property<int>("CustomerId").HasColumnType("int");
                b.Property<string>("AccountNumber").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("AccountStatus").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("OwnershipType").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("OwnershipStartDate").HasColumnType("datetime2");
                b.HasKey("CustomerId", "AccountNumber");
                b.HasIndex("AccountNumber");
                b.ToTable("CustomerAccounts");
            });

            modelBuilder.Entity("G_Net_29_EF04.Models.Manager", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("BranchId").HasColumnType("int");
                b.Property<string>("Email").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("HireDate").HasColumnType("datetime2");
                b.Property<string>("PhoneNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.HasKey("Id");
                b.HasIndex("BranchId").IsUnique();
                b.ToTable("Managers");
                b.HasData(
                    new { Id = 1, BranchId = 1, Email = "ahmed.hassan@bank.com", FullName = "Ahmed Hassan", HireDate = new DateTime(2018, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), PhoneNumber = "01001111111" },
                    new { Id = 2, BranchId = 2, Email = "sara.mohamed@bank.com",  FullName = "Sara Mohamed",  HireDate = new DateTime(2019, 7,  1, 0, 0, 0, 0, DateTimeKind.Unspecified), PhoneNumber = "01002222222" },
                    new { Id = 3, BranchId = 3, Email = "omar.khaled@bank.com",   FullName = "Omar Khaled",   HireDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), PhoneNumber = "01003333333" });
            });

            modelBuilder.Entity("G_Net_29_EF04.Models.Transaction", b =>
            {
                b.Property<int>("TransactionNumber").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionNumber"));
                b.Property<string>("AccountNumber").IsRequired().HasColumnType("nvarchar(20)");
                b.Property<decimal>("Amount").HasColumnType("decimal(18,2)");
                b.Property<string>("Note").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<DateTime>("TransactionDate").HasColumnType("datetime2");
                b.Property<string>("TransactionType").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("TransactionNumber");
                b.HasIndex("AccountNumber");
                b.ToTable("Transactions");
            });

            modelBuilder.Entity("G_Net_29_EF04.Models.Account", b =>
            {
                b.HasOne("G_Net_29_EF04.Models.Branch", "Branch")
                 .WithMany("Accounts")
                 .HasForeignKey("BranchId")
                 .OnDelete(DeleteBehavior.Restrict)
                 .IsRequired();
                b.Navigation("Branch");
            });

            modelBuilder.Entity("G_Net_29_EF04.Models.CustomerAccount", b =>
            {
                b.HasOne("G_Net_29_EF04.Models.Account", "Account")
                 .WithMany("CustomerAccounts")
                 .HasForeignKey("AccountNumber")
                 .OnDelete(DeleteBehavior.Cascade)
                 .IsRequired();
                b.HasOne("G_Net_29_EF04.Models.Customer", "Customer")
                 .WithMany("CustomerAccounts")
                 .HasForeignKey("CustomerId")
                 .OnDelete(DeleteBehavior.Cascade)
                 .IsRequired();
                b.Navigation("Account");
                b.Navigation("Customer");
            });

            modelBuilder.Entity("G_Net_29_EF04.Models.Manager", b =>
            {
                b.HasOne("G_Net_29_EF04.Models.Branch", "Branch")
                 .WithOne("Manager")
                 .HasForeignKey("G_Net_29_EF04.Models.Manager", "BranchId")
                 .OnDelete(DeleteBehavior.Restrict)
                 .IsRequired();
                b.Navigation("Branch");
            });

            modelBuilder.Entity("G_Net_29_EF04.Models.Transaction", b =>
            {
                b.HasOne("G_Net_29_EF04.Models.Account", "Account")
                 .WithMany("Transactions")
                 .HasForeignKey("AccountNumber")
                 .OnDelete(DeleteBehavior.Cascade)
                 .IsRequired();
                b.Navigation("Account");
            });

            modelBuilder.Entity("G_Net_29_EF04.Models.Account", b =>
            {
                b.Navigation("CustomerAccounts");
                b.Navigation("Transactions");
            });

            modelBuilder.Entity("G_Net_29_EF04.Models.Branch", b =>
            {
                b.Navigation("Accounts");
                b.Navigation("Manager");
            });

            modelBuilder.Entity("G_Net_29_EF04.Models.Customer", b =>
            {
                b.Navigation("CustomerAccounts");
            });
#pragma warning restore 612, 618
        }
    }
}
